/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 06 19:27:32 GMT 2018
 */

package uk.ac.sanger.artemis.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.NoSuchElementException;
import java.util.Set;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import uk.ac.sanger.artemis.util.CacheHashMap;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CacheHashMap_ESTest extends CacheHashMap_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CacheHashMap cacheHashMap0 = new CacheHashMap(0, (-1));
      Integer integer0 = new Integer((-1));
      cacheHashMap0.put("", integer0);
      cacheHashMap0.put(integer0, "");
      cacheHashMap0.put(integer0, "");
      assertEquals(2, cacheHashMap0.size());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CacheHashMap cacheHashMap0 = new CacheHashMap(0, (-1));
      Integer integer0 = new Integer((-1));
      cacheHashMap0.put(integer0, "");
      Object object0 = cacheHashMap0.put(integer0, "");
      assertEquals("", object0);
      assertNotNull(object0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CacheHashMap cacheHashMap0 = new CacheHashMap(0, 0);
      cacheHashMap0.get((Object) null);
      Object object0 = cacheHashMap0.getLastKey();
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CacheHashMap cacheHashMap0 = new CacheHashMap(0, (-1));
      Integer integer0 = new Integer((-1));
      cacheHashMap0.put("", integer0);
      Object object0 = cacheHashMap0.getLastKey();
      assertEquals("", object0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CacheHashMap cacheHashMap0 = new CacheHashMap(0, (-1));
      Integer integer0 = new Integer((-1));
      cacheHashMap0.put("", integer0);
      Object object0 = cacheHashMap0.get("");
      assertNotNull(object0);
      assertEquals((-1), object0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      CacheHashMap cacheHashMap0 = new CacheHashMap(1, 1);
      Set<Object> set0 = cacheHashMap0.keySet();
      Object object0 = new Object();
      cacheHashMap0.put(set0, object0);
      // Undeclared exception!
      try { 
        cacheHashMap0.put("", "");
        fail("Expecting exception: StackOverflowError");
      
      } catch(StackOverflowError e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      CacheHashMap cacheHashMap0 = null;
      try {
        cacheHashMap0 = new CacheHashMap((-2021), 0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Illegal initial capacity: -2021
         //
         verifyException("java.util.HashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      CacheHashMap cacheHashMap0 = new CacheHashMap(0, 0);
      cacheHashMap0.get((Object) null);
      Object object0 = cacheHashMap0.put((Object) null, " -|mmkTE");
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      CacheHashMap cacheHashMap0 = new CacheHashMap(0, 499);
      cacheHashMap0.get("");
      Object object0 = cacheHashMap0.put("", (Object) null);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      CacheHashMap cacheHashMap0 = new CacheHashMap(0, (-1));
      // Undeclared exception!
      try { 
        cacheHashMap0.getLastKey();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.LinkedList", e);
      }
  }
}
