/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 06 19:28:56 GMT 2018
 */

package uk.ac.sanger.artemis.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.DayOfWeek;
import java.time.chrono.ChronoLocalDate;
import java.util.Comparator;
import java.util.function.UnaryOperator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import uk.ac.sanger.artemis.util.FastVector;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FastVector_ESTest extends FastVector_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      FastVector fastVector0 = new FastVector();
      fastVector0.insertElementAfter(fastVector0, fastVector0);
      DayOfWeek dayOfWeek0 = DayOfWeek.WEDNESDAY;
      fastVector0.insertElementAfter(fastVector0, dayOfWeek0);
      assertFalse(fastVector0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      FastVector fastVector0 = new FastVector();
      Integer integer0 = new Integer(0);
      fastVector0.add((Object) integer0);
      fastVector0.setElementAt(integer0, 0);
      assertEquals(1, fastVector0.size());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      FastVector fastVector0 = new FastVector();
      Integer integer0 = new Integer(0);
      fastVector0.insertElementAfter(integer0, (Object) null);
      Object object0 = fastVector0.lastElement();
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      FastVector fastVector0 = new FastVector();
      // Undeclared exception!
      try { 
        fastVector0.setElementAt("htsjdk.samtools.util.Interval", (-550));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      FastVector fastVector0 = new FastVector();
      fastVector0.insertElementAfter("NUSs^@&N", "NUSs^@&N");
      Integer integer0 = new Integer((-1619));
      fastVector0.insertElementAfter(integer0, (Object) null);
      // Undeclared exception!
      try { 
        fastVector0.mysort((Comparator) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      FastVector fastVector0 = new FastVector();
      fastVector0.insertElementAfter("NUSs^@&c", "NUSs^@&c");
      Comparator<ChronoLocalDate> comparator0 = ChronoLocalDate.timeLineOrder();
      fastVector0.insertElementAfter(fastVector0, (Object) null);
      // Undeclared exception!
      try { 
        fastVector0.mysort(comparator0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.String cannot be cast to java.time.chrono.ChronoLocalDate
         //
         verifyException("java.util.TimSort", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      FastVector fastVector0 = new FastVector();
      Comparator<DayOfWeek> comparator0 = (Comparator<DayOfWeek>) mock(Comparator.class, new ViolatedAssumptionAnswer());
      FastVector fastVector1 = fastVector0.mysort(comparator0);
      fastVector1.insertElementAfter(fastVector1, fastVector0);
      fastVector0.insertElementAfter(fastVector1, fastVector1);
      // Undeclared exception!
      try { 
        fastVector0.insertElementAfter(fastVector0, fastVector0);
        fail("Expecting exception: StackOverflowError");
      
      } catch(StackOverflowError e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      FastVector fastVector0 = new FastVector();
      fastVector0.insertElementAfter(fastVector0, fastVector0);
      Comparator<FastVector> comparator0 = (Comparator<FastVector>) mock(Comparator.class, new ViolatedAssumptionAnswer());
      FastVector fastVector1 = fastVector0.mysort(comparator0);
      assertNotSame(fastVector1, fastVector0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      FastVector fastVector0 = new FastVector();
      Integer integer0 = new Integer(0);
      fastVector0.add((Object) integer0);
      // Undeclared exception!
      try { 
        fastVector0.add((Object) integer0);
        fail("Expecting exception: Error");
      
      } catch(Error e) {
         //
         // internal error - object added a second time
         //
         verifyException("uk.ac.sanger.artemis.util.FastVector", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      FastVector fastVector0 = new FastVector();
      // Undeclared exception!
      try { 
        fastVector0.add((Object) null);
        fail("Expecting exception: Error");
      
      } catch(Error e) {
         //
         // internal error - adding a null object
         //
         verifyException("uk.ac.sanger.artemis.util.FastVector", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      FastVector fastVector0 = new FastVector();
      UnaryOperator<Object> unaryOperator0 = UnaryOperator.identity();
      fastVector0.add((Object) unaryOperator0);
      Object object0 = fastVector0.lastElement();
      assertNotNull(object0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      FastVector fastVector0 = new FastVector();
      // Undeclared exception!
      try { 
        fastVector0.setElementAt((Object) null, 1);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 1, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      FastVector fastVector0 = new FastVector();
      // Undeclared exception!
      try { 
        fastVector0.lastElement();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
